### ISSUE TITLE
Translation on the blake2b

### ISSUE THREAD

**Issue by sidielnikov** [samuel-lucas6/Balloon.NET#3]
Hello Lucas, I'm sorry for such stupid questions, I am not a village in cryptography. Look please I correctly transferred the hash function to 

BalloonM.cs?

private static void Hash(Span<byte> hash, ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt)
    {
        using var blake2b = new IncrementalBLAKE2b(HashSize, password);
        blake2b.Update(salt);
        blake2b.Update(hash);
        blake2b.Finalize(hash);
    }

Ballon.cs
 private static void Hash(Span<byte> buffer, ulong counter, ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt = default)
    {
        Span<byte> ctr = stackalloc byte[8];
        BinaryPrimitives.WriteUInt64LittleEndian(ctr, counter);
        using var blake2b = new IncrementalBLAKE2b(HashSize, password);
        blake2b.Update(ctr);
        blake2b.Update(salt);
        blake2b.Finalize(buffer);
    }

 private static void IntsToBlock(Span<byte> idxBlock, int t, int m, int i)
    {
        BinaryPrimitives.WriteUInt64LittleEndian(idxBlock[..8], (ulong)t);
        BinaryPrimitives.WriteUInt64LittleEndian(idxBlock[8..16], (ulong)m);
        BinaryPrimitives.WriteUInt64LittleEndian(idxBlock[16..24], (ulong)i);
        using var blake2b = new IncrementalBLAKE2b(HashSize, idxBlock[..24]);
        blake2b.Finalize(idxBlock);
    }

if something is wrong, please answer the fixed functions

**Comment by samuel-lucas6** [comment]
No parameter should be passed in as the BLAKE2b key in all cases. Don't specify a key and instead use `Update()`. Hope that helps.

**Comment by sidielnikov** [comment]
So it should look like?

private static void Hash(Span<byte> buffer, ulong counter, ReadOnlySpan<byte> password, ReadOnlySpan<byte> salt = default)
    {
        Span<byte> ctr = stackalloc byte[8];
        BinaryPrimitives.WriteUInt64LittleEndian(ctr, counter);
        using var blake2b = new IncrementalBLAKE2b(HashSize);
        blake2b.Update(password);
        blake2b.Update(ctr);
        blake2b.Update(salt);
        blake2b.Finalize(buffer);
    }

    private static void IntsToBlock(Span<byte> idxBlock, int t, int m, int i)
    {
        BinaryPrimitives.WriteUInt64LittleEndian(idxBlock[..8], (ulong)t);
        BinaryPrimitives.WriteUInt64LittleEndian(idxBlock[8..16], (ulong)m);
        BinaryPrimitives.WriteUInt64LittleEndian(idxBlock[16..24], (ulong)i);
        using var blake2b = new IncrementalBLAKE2b(HashSize);
        blake2b.Update(idxBlock[..24]);
        blake2b.Finalize(idxBlock);
    }

**Comment by samuel-lucas6** [comment]
You seem to have the `password` and `ctr` the wrong way around in `Hash()`. The code for BLAKE2b is identical to what I wrote except `sha256` is replaced with `blake2b`.

**Comment by sidielnikov** [comment]
Thank you Lucas I figured out sorry for such stupid questions
